server:
  port: 8086

spring:
  application:
    name: DESIGN-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://saibenne:9573879821@cluster0.wg5hwhv.mongodb.net/?retryWrites=true&w=majority
      database: royaltheorem
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka



